apiVersion: apps/v1
kind: Deployment
metadata:
  name: real-estate-ai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: real-estate-ai
  template:
    metadata:
      labels:
        app: real-estate-ai
    spec:
      containers:
        - name: api
          image: real-estate-ai:latest
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: database-url
            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: redis-url
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: openai-api-key
            - name: PINECONE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: pinecone-api-key
            - name: TWILIO_ACCOUNT_SID
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: twilio-account-sid
            - name: TWILIO_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: twilio-auth-token
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: real-estate-ai
spec:
  selector:
    app: real-estate-ai
  ports:
    - port: 80
      targetPort: 8000
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: real-estate-ai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: real-estate-ai
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80
